rules:
  interop-001-only-https-server:
    documentationUrl: https://docs.developer.tech.gov.sg/docs/interop-linter/rules/openapi/001
    message: >
      Only HTTPS servers are allowed.
    description: >
      This rule ensures that all server URLs in the OpenAPI specification use the HTTPS protocol to comply with security best practices, ensuring encrypted communication and protecting sensitive data.
    severity: error
    given:
      - "$.servers[*].url"
      - "$.schemes[*]"
    then:
      function: pattern
      functionOptions:
        match: "^https$|^https://"
