name: Run Spectral on Pull Requests to Main

on:
  pull_request:
  push:
    branches: main

jobs:
  lint:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
